#!/usr/bin/env php
<?php
require_once("./tools/Cli.php");

use App\Cli;

execute($argv);

function execute($arguments)
{
    /* variables */
    $db_info = [];
    $db_connection = [];
    // remove file name from args
    $arguments = RemoveFileNameFromArguments($arguments);

    if (in_array("--help", $arguments)) {
        PrintHelp();
        die;
    }

    $db_info = GetDataBaseParams($arguments);
    $db_connection = [
        "3.1" => mysqli_connect($db_info["3.1"]["host"], $db_info["3.1"]["username"], $db_info["3.1"]["password"], $db_info["3.1"]["name"]),
        "3.3" => mysqli_connect($db_info["3.3"]["host"], $db_info["3.3"]["username"], $db_info["3.3"]["password"], $db_info["3.3"]["name"])
    ];

    // load 3.3 submission id list
    $submission_id_list = mysqli_fetch_all(mysqli_query($db_connection['3.3'], "SELECT submission_id FROM `submissions`"));

    foreach ($submission_id_list as $key => $value) {
        // load submission authors
        $query = mysqli_query($db_connection["3.3"], "SELECT publication_id,author_id FROM `authors` WHERE `publication_id`=" . $value[0]);
        if ($query == false) {
            continue;
        }
        $submission_authors = mysqli_fetch_all($query);
        
    }
}

/**
 * Removes the current file name from the provided array of arguments.
 *
 * This function iterates through the array of arguments and removes any
 * element that has the same value as the base name of the current file.
 *
 * @param array $arguments The array of arguments to process.
 *
 * @return array The updated array with the current file name removed.
 */
function RemoveFileNameFromArguments($arguments)
{
    foreach ($arguments as $key => $value) {
        if ($value === basename(__FILE__)) {
            unset($arguments[$key]);
        }
    }
    return $arguments;
}

/**
 * Prints help information for the CLI application.
 *
 * This function prints a help message describing the usage of the CLI application,
 * including the expected command-line arguments.
 *
 * Example:
 *   php script.php filename [ojs-3.1 database name] [ojs-3.3 database name]
 *
 * @return void
 */
function PrintHelp()
{
    Cli::print("\nhelp : filename [ojs-3.1 database name]:[username]:[password]:[host] [ojs-3.3 database name]:[username]:[password]:[host]\n");
}

/**
 * Parses command line arguments to extract database parameters.
 *
 * @param array $arguments The array of command line arguments.
 *
 * @return array Associative array containing database parameters for OJS 3.1 and OJS 3.3.
 */
function GetDataBaseParams($arguments)
{
    $temp = explode(":", $arguments[1]);
    $template["3.1"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    $temp = explode(":", $arguments[2]);
    $template["3.3"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    return $template;
}