#!/usr/bin/env php
<?php
require_once("./tools/Cli.php");

use App\Cli;

execute($argv);

function execute($arguments)
{
    /* variables */
    $db_info = [];
    $db_connection = [];
    $publications = [];
    // remove file name from args
    $arguments = RemoveFileNameFromArguments($arguments);
    if (in_array("--help", $arguments)) {
        PrintHelp();
        die;
    }
    $db_info = GetDataBaseParams($arguments);
    $db_connection = [
        "3.1" => mysqli_connect($db_info["3.1"]["host"], $db_info["3.1"]["username"], $db_info["3.1"]["password"], $db_info["3.1"]["name"]),
        "3.3" => mysqli_connect($db_info["3.3"]["host"], $db_info["3.3"]["username"], $db_info["3.3"]["password"], $db_info["3.3"]["name"])
    ];
    $publications = mysqli_fetch_all(mysqli_query($db_connection["3.3"], "SELECT * FROM `publications` WHERE `status`=3"));
    $counter = 1;
    foreach ($publications as $key => $value) {
        $query = mysqli_query($db_connection["3.1"], "SELECT * FROM `published_submissions` WHERE `submission_id`=" . $value[8]);
        if ($query == false) {
            continue;
        }
        $published_date = mysqli_fetch_row($query)[3];
        $query = mysqli_query($db_connection["3.3"], "UPDATE `publications` SET `date_published`='" . $published_date . "' WHERE `submission_id`=" . $value[8]);
        if ($query == false) {
            Cli::print_error("Update Failed\n");
            die;
        }
        Cli::print_success("Submission #" . $value[8] . " published_date updated!");
        $counter++;
    }
    Cli::print("\n");
    Cli::print("\n");
    Cli::print_success("Update " . $counter . " submission dates successfully!\n");
}

/**
 * Removes the current file name from the provided array of arguments.
 *
 * This function iterates through the array of arguments and removes any
 * element that has the same value as the base name of the current file.
 *
 * @param array $arguments The array of arguments to process.
 *
 * @return array The updated array with the current file name removed.
 */
function RemoveFileNameFromArguments($arguments)
{
    foreach ($arguments as $key => $value) {
        if ($value === basename(__FILE__)) {
            unset($arguments[$key]);
        }
    }
    return $arguments;
}

/**
 * Prints help information for the CLI application.
 *
 * This function prints a help message describing the usage of the CLI application,
 * including the expected command-line arguments.
 *
 * Example:
 *   php script.php filename [ojs-3.1 database name] [ojs-3.3 database name]
 *
 * @return void
 */
function PrintHelp()
{
    Cli::print("\nhelp : filename [ojs-3.1 database name]:[username]:[password]:[host] [ojs-3.3 database name]:[username]:[password]:[host]\n");
}

/**
 * Parses command line arguments to extract database parameters.
 *
 * @param array $arguments The array of command line arguments.
 *
 * @return array Associative array containing database parameters for OJS 3.1 and OJS 3.3.
 */
function GetDataBaseParams($arguments)
{
    $temp = explode(":", $arguments[1]);
    $template["3.1"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    $temp = explode(":", $arguments[2]);
    $template["3.3"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    return $template;
}