#!/usr/bin/env php
<?php
require_once("./tools/Cli.php");

use App\Cli;

execute($argv);

function execute($arguments)
{
    /* variables */
    $db_info = [];
    $db_connection = [];
    // remove file name from args
    $arguments = RemoveFileNameFromArguments($arguments);

    if (in_array("--help", $arguments)) {
        PrintHelp();
        die;
    }

    $db_info = GetDataBaseParams($arguments);
    $db_connection = [
        "3.1" => mysqli_connect($db_info["3.1"]["host"], $db_info["3.1"]["username"], $db_info["3.1"]["password"], $db_info["3.1"]["name"]),
        "3.3" => mysqli_connect($db_info["3.3"]["host"], $db_info["3.3"]["username"], $db_info["3.3"]["password"], $db_info["3.3"]["name"])
    ];

    // load 3.3 submission id list
    $submission_id_list = mysqli_fetch_all(mysqli_query($db_connection['3.3'], "SELECT submission_id FROM `submissions`"));

    // Step 1 - Remove admin admin contributors from authors
    RemoveAdminAuthors($submission_id_list, $db_connection);
    die;
    // Step 2 - 

    foreach ($submission_id_list as $key => $value) {
        // load submission authors
        $query = mysqli_query($db_connection["3.3"], "SELECT publication_id,author_id FROM `authors` WHERE `publication_id`=" . $value[0]);
        if ($query == false) {
            continue;
        }
        $submission_authors = mysqli_fetch_all($query);
        foreach ($submission_authors as $author_key => $author_value) {
            $author_data = mysqli_fetch_row(mysqli_query($db_connection["3.1"], "SELECT * FROM `authors` WHERE `"));
            var_dump($author_data);
            // Cli::print($author_data);
            // $author_email_query = mysqli_query($db_connection["3.3"], "UPDATE `authors` SET `author_id`='[value-1]' WHERE `email`=''");
        }
    }
}

/**
 * Removes the current file name from the provided array of arguments.
 *
 * This function iterates through the array of arguments and removes any
 * element that has the same value as the base name of the current file.
 *
 * @param array $arguments The array of arguments to process.
 *
 * @return array The updated array with the current file name removed.
 */
function RemoveFileNameFromArguments($arguments)
{
    foreach ($arguments as $key => $value) {
        if ($value === basename(__FILE__)) {
            unset($arguments[$key]);
        }
    }
    return $arguments;
}

/**
 * Prints help information for the CLI application.
 *
 * This function prints a help message describing the usage of the CLI application,
 * including the expected command-line arguments.
 *
 * Example:
 *   php script.php filename [ojs-3.1 database name] [ojs-3.3 database name]
 *
 * @return void
 */
function PrintHelp()
{
    Cli::print("\nhelp : filename [ojs-3.1 database name]:[username]:[password]:[host] [ojs-3.3 database name]:[username]:[password]:[host]\n");
}

/**
 * Parses command line arguments to extract database parameters.
 *
 * @param array $arguments The array of command line arguments.
 *
 * @return array Associative array containing database parameters for OJS 3.1 and OJS 3.3.
 */
function GetDataBaseParams($arguments)
{
    $temp = explode(":", $arguments[1]);
    $template["3.1"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    $temp = explode(":", $arguments[2]);
    $template["3.3"] = [
        "name" => $temp[0],
        "username" => $temp[1],
        "password" => $temp[2],
        "host" => $temp[3],
    ];
    return $template;
}

function RemoveAdminAuthors($submission_id_list, $db_connection)
{
    Cli::print("\n Delete admin authors & author_settings\n");

    // get all data from author_settings with setting_value = "admin"
    $get_all_author_setting = mysqli_fetch_all(mysqli_query($db_connection["3.3"], "SELECT * FROM `author_settings` WHERE `setting_value`='admin'"));

    Cli::print("Clean authors");
    // delete authors
    foreach ($get_all_author_setting as $auth_key => $auth_value) {
        $get_author_query = mysqli_query($db_connection["3.3"], "SELECT * FROM `authors` WHERE `author_id`=" . $auth_value[0]);
        if ($get_author_query == false) {
            continue;
        }
        mysqli_query($db_connection["3.3"], "DELETE FROM `authors` WHERE `author_id`=" . $auth_value[0]);
        Cli::print_success("reocrd (author_id)#" . $auth_value[0] . " successfully deleted.");
    }
    Cli::print_success("Clean authors successfully!");

    Cli::print("\nClean author_settings");
    // delete author settings
    foreach ($get_all_author_setting as $author_setting_key => $author_setting_value) {
        $author_setting_all_data = mysqli_fetch_all(mysqli_query($db_connection["3.3"], "SELECT * FROM `author_settings` WHERE `author_id`=" . $author_setting_value[0]));
        foreach ($author_setting_all_data as $author_setting_all_data_key => $author_setting_all_data_value) {
            mysqli_query($db_connection["3.3"], "DELETE FROM `author_settings` WHERE `author_settings`.`author_id` = " . $author_setting_all_data_value[0] .
                " AND `author_settings`.`locale` = '" . $author_setting_all_data_value[1] . "' AND `author_settings`.`setting_name` = '" .
                $author_setting_all_data_value[2] . "' AND `author_settings`.`setting_value` = '" . $author_setting_all_data_value[3] . "'");
            Cli::print_success("reocrd (author_id)#" . $author_setting_all_data_value[0] . " successfully deleted.");
        }
    }
    Cli::print_success("Clean author_settings successfully!\n");
}